//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.09.27 at 01:22:27 PM CEST 
//


package com.klst.iban;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.klst.iban package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.klst.iban
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Result }
     * 
     */
    public Result createResult() {
        return new Result();
    }

    /**
     * Create an instance of {@link Result.Validations }
     * 
     */
    public Result.Validations createResultValidations() {
        return new Result.Validations();
    }

    /**
     * Create an instance of {@link Result.BankData }
     * 
     */
    public Result.BankData createResultBankData() {
        return new Result.BankData();
    }

    /**
     * Create an instance of {@link Result.SepaData }
     * 
     */
    public Result.SepaData createResultSepaData() {
        return new Result.SepaData();
    }

    /**
     * Create an instance of {@link Result.Validations.Chars }
     * 
     */
    public Result.Validations.Chars createResultValidationsChars() {
        return new Result.Validations.Chars();
    }

    /**
     * Create an instance of {@link Result.Validations.Iban }
     * 
     */
    public Result.Validations.Iban createResultValidationsIban() {
        return new Result.Validations.Iban();
    }

    /**
     * Create an instance of {@link Result.Validations.Account }
     * 
     */
    public Result.Validations.Account createResultValidationsAccount() {
        return new Result.Validations.Account();
    }

    /**
     * Create an instance of {@link Result.Validations.Structure }
     * 
     */
    public Result.Validations.Structure createResultValidationsStructure() {
        return new Result.Validations.Structure();
    }

    /**
     * Create an instance of {@link Result.Validations.Length }
     * 
     */
    public Result.Validations.Length createResultValidationsLength() {
        return new Result.Validations.Length();
    }

    /**
     * Create an instance of {@link Result.Validations.CountrySupport }
     * 
     */
    public Result.Validations.CountrySupport createResultValidationsCountrySupport() {
        return new Result.Validations.CountrySupport();
    }

}
